### ISSUE TITLE
Model find by id should retun an Optional

### ISSUE THREAD

**Issue by timominous** [qutheory/fluent#29]
I think it would be better if find returned an optional instead of throwing an exception when nothing is found.

**Comment by Evertt** [comment]
Hmm, I gave it a +1, but now that I think more about it, I'm more neutral.

What I **like** about your proposal:

1. It feels more "correct" to return an optional, because if you can't find a model then you didn't do anything wrong. A dictionary also doesn't throw an exception if it can't find the key that you asked for.
2. I find code that deals with catching errors quite ugly and I prefer to read code that deals with unpacking optionals.

What I **don't like** about your proposal:

1. I find it nice and easy if the controller doesn't have to deal with the option that a model doesn't exist and a 404-exception is just thrown automagically.

**Comment by tannernelson** [comment]
@timominous this is something we discussed in the Qutheory Slack. We ended up deciding on `throw` because that allows the user to opt in to optional behavior by doing `try?`

**Comment by timominous** [comment]
I see. Things get burried in Slack quite easily. Lol. I agree, using `try?` would be a better option.
